import turtle
t=turtle.Turtle()
t.hideturtle()
turtle.bgcolor('black')
#making window
t.penup()
t.setposition(-100,100)
t.pendown()
t.begin_fill()
t.fillcolor('#00adef')
t.pencolor('#00adef')
t.left(10)
t.forward(200)
t.right(100)
t.forward(220)
t.right(100)
t.forward(200)
t.right(80)
t.forward(153)
t.end_fill()
#making line to cut window
t.penup()
t.setposition(-100,34)
t.pendown()
t.right(90)
t.width(10)
t.color('black')
t.fd(200)

t.penup()
t.setposition(0,200)
t.right(90)
t.pendown()
t.fd(300)
#writing windows
t.goto(-80,-150)
t.color('white')
t.write('Windows',font=('Times New Roman',30,'italic','bold'))
turtle.done()